### ISSUE TITLE
The "order by" has incorrect order

### ISSUE THREAD

**Issue by prsolucoes** [AlexDenisov/iActiveRecord#89]
The "order by" has incorrect order. Example:

```
[fetcherChapters orderBy:@"sequence"];
[fetcherChapters orderBy:@"id"];
```

When iActiveRecord create the "order by" query, it creates:

```
id ASC, sequence ASC
```

But the problem is not with iActiveRecord, the problem is with NSMutableDictionary. The method "orderBy" use a NSMutableDictionary to store the "orderBy" sentences. But NSMutableDictionary automatically order the items alphabetically.

Have any way to solve it?

**Comment by AlexDenisov** [comment]
The only way I see is to fix implementation...

**Comment by prsolucoes** [comment]
Have any apple dictionary or mutable array that i can use without auto sort?

**Comment by AlexDenisov** [comment]
The easiest way I see is to create a kinda model/tuple to store these values, e.g.:

```objc
enum SortOrder { SortOrderASC, SortOrderDESC };
@interface ARSort : NSObject
@property NSString *name;
@property SortOrder order;
@end
```
and put the instances into `NSArray/NSMutableArray`.

**Comment by prsolucoes** [comment]
I solve the problem. Will make a PR.

**Comment by prsolucoes** [comment]
https://github.com/AlexDenisov/iActiveRecord/pull/90

**Comment by prsolucoes** [comment]
Can you check? Here is working perfect.
